version: '3.8'

services:
  minio:
    mem_limit: 512m
    container_name: docs_minio_container
    image: 'bitnami/minio:latest'
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - 'minio_data:/data'
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER:-minio}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD:-miniosecret}
      - MINIO_SCHEME=http
      - MINIO_REGION_NAME=${S3_REGION:-us-east-1}
      - MINIO_DEFAULT_BUCKETS=${S3_BUCKET_NAME}
      
  postgres:
    container_name: docs_postgres_container
    image: postgres:14.3-alpine3.15
    mem_limit: 2000m
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - '${POSTGRES_PORT:-5432}:5432'
    networks:
      - postgres
    restart: unless-stopped

  pgadmin:
    container_name: docs_pgadmin_container
    mem_limit: 256m
    image: dpage/pgadmin4:6.10
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    volumes:
      - pgadmin:/root/.pgadmin
    ports:
      - '${PGADMIN_PORT:-5056}:80'
    networks:
      - postgres
    restart: unless-stopped
    
networks:
  postgres:
    driver: bridge

volumes:
  postgres:
  pgadmin:
  minio_data:
    driver: local
