export enum NotificationType {
  MACHINERY = 'MACHINERY',
  PROMOTION = 'PROMOTION',
  NEWS_COMMON = 'NEWS_COMMON',
  NEWS_BIZONAGRO = 'NEWS_BIZONAGRO',
  COMMON_SERVICE = 'COMMON_SERVICE',
  USED_MACHINERY_MODERATION = 'USED_MACHINERY_MODERATION',
  TEXT = 'TEXT',
}
