export enum VerificationType {
  INDIVIDUAL_REGISTRATION = 'INDIVIDUAL_REGISTRATION',
  INDIVIDUAL_AUTHORIZATION = 'INDIVIDUAL_AUTHORIZATION',
  ENTREPRENEUR_REGISTRATION = 'ENTREPRENEUR_REGISTRATION',
  FORGOT_PASSWORD = 'FORGOT_PASSWORD',
}
